Logging to ./experiments/log/
creating model...
  0%|                                                                                                                                | 0/100000 [00:00<?, ?it/s]
creating data loader...
  0%|                                                                                                                                | 0/100000 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/labuser/AT_DDPM/scripts/AT_train.py", line 107, in <module>
    main(run)
  File "/home/labuser/AT_DDPM/scripts/AT_train.py", line 52, in main
    TrainLoop(
  File "/home/labuser/AT_DDPM/guided_diffusion/train_util.py", line 160, in run_loop
    self.test(run, phase='train', skip_timesteps=0, iter = i)
  File "/home/labuser/AT_DDPM/guided_diffusion/train_util.py", line 143, in test
    diffusion_test( self.val_data, self.model,self.diffusion,'./results', run, phase, skip_timesteps,iter )
  File "/home/labuser/AT_DDPM/guided_diffusion/test_diff.py", line 48, in diffusion_test
    sample = diffusion.p_sample_loop(
  File "/home/labuser/AT_DDPM/guided_diffusion/gaussian_diffusion.py", line 459, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/labuser/AT_DDPM/guided_diffusion/gaussian_diffusion.py", line 511, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/labuser/AT_DDPM/guided_diffusion/gaussian_diffusion.py", line 408, in p_sample
    out = self.p_mean_variance(
  File "/home/labuser/AT_DDPM/guided_diffusion/respace.py", line 91, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/labuser/AT_DDPM/guided_diffusion/gaussian_diffusion.py", line 251, in p_mean_variance
    assert model_output.shape == (B, C * 2, *x.shape[2:])
AssertionError